<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <BaseOutputPath></BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="OrTemplate - Копировать.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="postcopy.bat" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="postcopy.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include="LogicTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LogicTemplate.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PluginSupport\PluginSupport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LogicTemplate.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>LogicTemplate.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="LogicTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LogicTemplate.tt</DependentUpon>
    </Compile>
    <Compile Update="OrTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OrTemplate.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="call postcopy.bat" />
  </Target>

</Project>
