<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <BaseOutputPath>C:\MyWork\CodeGeneration\CodeGenerator\bin\Debug\net9.0-windows\Plugins</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PluginSupport\PluginSupport.csproj" />
  </ItemGroup>

</Project>
