<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <BaseOutputPath></BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="postcopy.bat" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="postcopy.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PluginSupport\PluginSupport.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="call postcopy.bat" />
  </Target>

</Project>
